version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - isolated_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - isolated_network

networks:
  isolated_network:
    driver: bridge
